# Generated by Django 3.0.8 on 2020-08-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='country',
            new_name='default_country',
        ),
    ]
