# Generated by Django 3.0.8 on 2020-08-24 11:07

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200824_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='default_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
