# Generated by Django 3.0.8 on 2020-08-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200824_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='default_first_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='default_last_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
