# Generated by Django 3.0.8 on 2020-08-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='included',
            options={'verbose_name_plural': 'Included'},
        ),
    ]
